<h1 style="text-align:center;  border-bottom: 2px solid #1E90FF;">
  Petrophysical Data Analysis
</h1>

1. Loading and exploring well log LAS files using Lasio
2. Using the Welly Python library for working with multiple LAS files
3. Combining well log data with formation tops
4. Integrating core data with log data
5. Well log visualizations in Python
6. Well log data preprocessing


<hr style="border: 0; height: 2px; background-color: #1E90FF;">

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import lasio #pip install lasio

import warnings
warnings.filterwarnings('ignore')

<h3 style="text-align:left; color:#1E90FF;">
  1. Loading and Exploring Well Log LAS Files using Lasio
</h3>

Note: LAS (Log ASCII Standard) is the industry standard format for well log data. Lasio efficiently handles this format, allowing for easy integration with pandas for further analysis.

In [31]:
well = lasio.read(r"C:\Users\hp\Coding World\PE-Petrophysical Analytics\Datasets\wells\well1.las")

df = well.df()

df

,ABDCQF01,ABDCQF02,ABDCQF03,ABDCQF04,BS,CALI,DRHO,DT,DTS,GR,...,PEF,RACEHM,RACELM,RD,RHOB,RM,ROP,RPCEHM,RPCELM,RT
DEPTH,,,,,,,,,,,,,,,,,,,,,
188.5,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,4.300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188.6,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,3.801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188.7,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,4.301,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188.8,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,4.600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188.9,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,4.599,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3761.5,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19.738,NaN,NaN,NaN
3761.6,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19.751,NaN,NaN,NaN
3761.7,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19.764,NaN,NaN,NaN
3761.8,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19.757,NaN,NaN,NaN
3761.9,NaN,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19.744,NaN,NaN,NaN

In [32]:
df.shape

(35735, 21)

In [33]:
df.head()

,ABDCQF01,ABDCQF02,ABDCQF03,ABDCQF04,BS,CALI,DRHO,DT,DTS,GR,...,PEF,RACEHM,RACELM,RD,RHOB,RM,ROP,RPCEHM,RPCELM,RT
DEPTH,,,,,,,,,,,,,,,,,,,,,
188.5,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,4.300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188.6,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,3.801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188.7,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,4.301,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188.8,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,4.600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188.9,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,4.599,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df.describe()

,ABDCQF01,ABDCQF02,ABDCQF03,ABDCQF04,BS,CALI,DRHO,DT,DTS,GR,...,PEF,RACEHM,RACELM,RD,RHOB,RM,ROP,RPCEHM,RPCELM,RT
count,12468.0000000000,12333.0000000000,11896.0000000000,12325.0000000000,35735.0000000000,11681.0000000000,11688.0000000000,11475.0000000000,11084.0000000000,35591.0000000000,...,11625.0000000000,11878.0000000000,11878.0000000000,35165.0000000000,11625.0000000000,35165.0000000000,35349.0000000000,11826.0000000000,11844.0000000000,35165.0000000000
mean,2.4436335419,2.4497197762,2.4591886348,2.4381759026,17.3609890863,8.6336576492,0.0575841889,77.7641352505,145.3342329484,52.2705105504,...,7.3172731183,10.4315873043,3.2014740697,1.9706398123,2.4680207312,34.4009041092,25.4601778268,119.4444039405,3.9067749916,34.4009041092
std,0.2228197593,0.1767711786,0.1808165615,0.1964867859,7.2229130462,0.0526753870,0.0117784196,15.5736345389,44.3772353156,39.8731402417,...,1.2311206402,194.4937763011,10.0092834249,4.2920952295,0.1527992810,1333.6931981372,13.9596191830,2461.4107251646,7.0600454004,1333.6931981372
min,-6.3610000000,1.6370000000,1.3180000000,1.0320000000,8.5000000000,7.9930000000,-0.1520000000,53.1650000000,83.5740000000,0.5140000000,...,4.7610000000,0.0900000000,-0.0500000000,0.0840000000,2.0330000000,0.1030000000,0.0000000000,0.1030000000,0.0840000000,0.1030000000
25%,2.2830000000,2.2870000000,2.3130000000,2.2820000000,8.5000000000,8.6250000000,0.0530000000,66.1980000000,119.4520000000,20.2425000000,...,6.4610000000,1.5600000000,1.5720000000,0.7360000000,2.3370000000,0.7690000000,18.4770000000,1.7292500000,1.6150000000,0.7690000000
50%,2.5150000000,2.5240000000,2.5320000000,2.5190000000,17.5000000000,8.6250000000,0.0590000000,71.5940000000,129.9030000000,55.0360000000,...,7.8170000000,2.4935000000,2.5400000000,1.1220000000,2.5280000000,1.1950000000,23.8110000000,3.0380000000,2.6430000000,1.1950000000
75%,2.5760000000,2.5830000000,2.5860000000,2.5790000000,26.0000000000,8.6720000000,0.0630000000,87.7180000000,145.4955000000,75.4275000000,...,8.2970000000,4.0800000000,4.0227500000,1.9750000000,2.5810000000,2.1110000000,31.0580000000,4.9450000000,4.3950000000,2.1110000000
max,3.0410000000,3.0520000000,3.1160000000,3.0300000000,36.0000000000,9.1320000000,0.1820000000,126.8270000000,343.9440000000,1124.4030000000,...,13.8410000000,6381.0990000000,662.1170000000,202.1590000000,3.0250000000,62290.7700000000,193.0840000000,62290.7700000000,202.1610000000,62290.7700000000

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ABDCQF01,12468.0,2.443634,0.222820,-6.361,2.28300,2.5150,2.57600,3.041
ABDCQF02,12333.0,2.449720,0.176771,1.637,2.28700,2.5240,2.58300,3.052
ABDCQF03,11896.0,2.459189,0.180817,1.318,2.31300,2.5320,2.58600,3.116
ABDCQF04,12325.0,2.438176,0.196487,1.032,2.28200,2.5190,2.57900,3.030
BS,35735.0,17.360989,7.222913,8.500,8.50000,17.5000,26.00000,36.000
CALI,11681.0,8.633658,0.052675,7.993,8.62500,8.6250,8.67200,9.132
DRHO,11688.0,0.057584,0.011778,-0.152,0.05300,0.0590,0.06300,0.182
DT,11475.0,77.764135,15.573635,53.165,66.19800,71.5940,87.71800,126.827
DTS,11084.0,145.334233,44.377235,83.574,119.45200,129.9030,145.49550,343.944
GR,35591.0,52.270511,39.873140,0.514,20.24250,55.0360,75.42750,1124.403
NPHI,11597.0,0.165921,0.099208,0.010,0.09300,0.1310,0.22200,0.559
PEF,11625.0,7.317273,1.231121,4.761,6.46100,7.8170,8.29700,13.841
RACEHM,11878.0,10.431587,194.493776,0.090,1.56000,2.4935,4.08000,6381.099
RACELM,11878.0,3.201474,10.009283,-0.050,1.57200,2.5400,4.02275,662.117
RD,35165.0,1.970640,4.292095,0.084,0.73600,1.1220,1.97500,202.159
RHOB,11625.0,2.468021,0.152799,2.033,2.33700,2.5280,2.58100,3.025
RM,35165.0,34.400904,1333.693198,0.103,0.76900,1.1950,2.11100,62290.770
ROP,35349.0,25.460178,13.959619,0.000,18.47700,23.8110,31.05800,193.084
RPCEHM,11826.0,119.444404,2461.410725,0.103,1.72925,3.0380,4.94500,62290.770
RPCELM,11844.0,3.906775,7.060045,0.084,1.61500,2.6430,4.39500,202.161
RT,35165.0,34.400904,1333.693198,0.103,0.76900,1.1950,2.11100,62290.770

In [35]:
df.columns

Index(['ABDCQF01', 'ABDCQF02', 'ABDCQF03', 'ABDCQF04', 'BS', 'CALI', 'DRHO',
       'DT', 'DTS', 'GR', 'NPHI', 'PEF', 'RACEHM', 'RACELM', 'RD', 'RHOB',
       'RM', 'ROP', 'RPCEHM', 'RPCELM', 'RT'],
      dtype='object')

In [36]:
cols = ['CALI', 'DRHO', 'DT', 'DTS', 'GR', 'NPHI','RHOB', 'RT']

df = df[cols]

df

        CALI  DRHO  DT  DTS     GR  NPHI  RHOB  RT
DEPTH
188.5    NaN   NaN NaN  NaN  4.300   NaN   NaN NaN
188.6    NaN   NaN NaN  NaN  3.801   NaN   NaN NaN
188.7    NaN   NaN NaN  NaN  4.301   NaN   NaN NaN
188.8    NaN   NaN NaN  NaN  4.600   NaN   NaN NaN
188.9    NaN   NaN NaN  NaN  4.599   NaN   NaN NaN
...      ...   ...  ..  ...    ...   ...   ...  ..
3761.5   NaN   NaN NaN  NaN    NaN   NaN   NaN NaN
3761.6   NaN   NaN NaN  NaN    NaN   NaN   NaN NaN
3761.7   NaN   NaN NaN  NaN    NaN   NaN   NaN NaN
3761.8   NaN   NaN NaN  NaN    NaN   NaN   NaN NaN
3761.9   NaN   NaN NaN  NaN    NaN   NaN   NaN NaN

[35735 rows x 8 columns]

In [37]:
# df['DEPTH'] = df.index

df.head()

       CALI  DRHO  DT  DTS     GR  NPHI  RHOB  RT
DEPTH
188.5   NaN   NaN NaN  NaN  4.300   NaN   NaN NaN
188.6   NaN   NaN NaN  NaN  3.801   NaN   NaN NaN
188.7   NaN   NaN NaN  NaN  4.301   NaN   NaN NaN
188.8   NaN   NaN NaN  NaN  4.600   NaN   NaN NaN
188.9   NaN   NaN NaN  NaN  4.599   NaN   NaN NaN

In [17]:
df.isnull().sum()

CALI     24054
DRHO     24047
DT       24260
DTS      24651
GR         144
NPHI     24138
RHOB     24110
RT         570
Depth        0
DEPTH        0
dtype: int64

In [18]:
df.replace(-999.25, np.nan, inplace=True)
df.isnull().sum()

CALI     24054
DRHO     24047
DT       24260
DTS      24651
GR         144
NPHI     24138
RHOB     24110
RT         570
Depth        0
DEPTH        0
dtype: int64

<h3 style="text-align:left; color:#1E90FF;">
  2. Welly Python Library for Working with Multiple LAS Files
</h3>

Welly builds on lasio to provide a more comprehensive toolkit for working with well data, including support for multiple wells and advanced curve operations.

In [21]:
import welly # pip install welly
from welly import Project

field = Project.from_las(r'C:\Users\hp\Coding World\PE-Petrophysical Analytics\Datasets\*.las')

field

0it [00:00, ?it/s]

2it [00:01,  1.50it/s]

Project(2 wells: , )

In [22]:
field = Project.from_las(r'C:\Users\hp\Coding World\PE-Petrophysical Analytics\Datasets\wells\*.las')

field

3it [00:11,  3.88s/it]

Project(3 wells: 11A, , 15/9-13)

In [23]:
well1 = field.get_well("11A")

well1

Well(uwi: '11A', name: '15/9-F-11 A', 21 curves: ['ABDCQF01', 'ABDCQF02', 'ABDCQF03', 'ABDCQF04', 'BS', 'CALI', 'DRHO', 'DT', 'DTS', 'GR', 'NPHI', 'PEF', 'RACEHM', 'RACELM', 'RD', 'RHOB', 'RM', 'ROP', 'RPCEHM', 'RPCELM', 'RT'])

In [27]:
well1.header.keys()

well1.uwi

'11A'

In [28]:
gamma_ray = well1.data['GR']
gamma_ray

Curve(mnemonic=GR, units=API, start=188.5000, stop=3761.9000, step=0.1000, count=[35591])

<h3 style="text-align:left; color:#1E90FF;">
  3. Combining Well Log Data with Formation Tops
</h3>

Formation tops represent the depths at which different geological formations are encountered in the well. Integrating this with log data provides crucial context for petrophysical analysis.

In [29]:
tops = pd.read_csv(r'C:\Users\hp\Coding World\PE-Petrophysical Analytics\Datasets\formation_tops.csv')

tops.head()

     MD  FORMATION   TVD  THICKNESS
0   557      Shale   554        441
1   998  Sandstone   995        168
2  1167  Limestone  1163         11
3  1175   Dolomite  1174        283
4  1458  Siltstone  1457         20

In [40]:
merged_data = pd.merge(df, tops, left_on = 'DEPTH', right_on='TVD', how='left')

merged_data

,CALI,DRHO,DT,DTS,GR,NPHI,RHOB,RT,MD,FORMATION,TVD,THICKNESS
0,NaN,NaN,NaN,NaN,4.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,3.801,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,4.301,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,4.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,4.599,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
35730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
merged_data['FORMATION'] = merged_data['FORMATION'].fillna(method='ffill')

merged_data

,CALI,DRHO,DT,DTS,GR,NPHI,RHOB,RT,MD,FORMATION,TVD,THICKNESS
0,NaN,NaN,NaN,NaN,4.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,3.801,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,4.301,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,4.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,4.599,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
35730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sandstone,NaN,NaN
35731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sandstone,NaN,NaN
35732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sandstone,NaN,NaN
35733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sandstone,NaN,NaN
35734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sandstone,NaN,NaN

<h3 style="text-align:left; color:#1E90FF;">
  4. Combining Core Data with Log Data
</h3>

Core data provides direct measurements of rock properties but is only available at specific depths. Combining it with continuous log data allows for calibration and improved interpretation.

In [42]:
core_data = pd.read_csv(r'C:\Users\hp\Coding World\PE-Petrophysical Analytics\Notes\core_data.csv')

core_data.head()

   DEPTH        GR_CORE      PHI_CORE         K_CORE
0    188  48.1997618490  0.1457696567   5.7974635521
1    212  48.9044613154  0.1308807731  80.4410743659
2    236  55.9202134053  0.1864759657  32.7505853724
3    260  46.6124837151  0.1844502010   0.7511765610
4    284  56.5555830636  0.2132305695   2.1190700193

In [43]:
interpolated_logs = df.reindex(core_data['DEPTH']).interpolate()

interpolated_logs

        CALI   DRHO      DT      DTS      GR   NPHI   RHOB      RT
DEPTH
188      NaN    NaN     NaN      NaN     NaN    NaN    NaN     NaN
212      NaN    NaN     NaN      NaN  10.899    NaN    NaN   0.394
236      NaN    NaN     NaN      NaN  22.499    NaN    NaN   1.436
260      NaN    NaN     NaN      NaN  23.299    NaN    NaN   1.990
284      NaN    NaN     NaN      NaN  34.997    NaN    NaN   1.249
...      ...    ...     ...      ...     ...    ...    ...     ...
3596   8.625  0.051  86.126  141.323  18.932  0.149  2.259  16.773
3620   8.672  0.072  85.501  151.310  50.827  0.180  2.472   1.802
3644   8.688  0.055  92.438  147.409  41.952  0.216  2.256   2.480
3668   8.625  0.052  93.757  149.604  37.761  0.225  2.197   4.425
3692   8.594  0.054  88.646  141.760  30.583  0.214  2.258   5.076

[147 rows x 8 columns]

<h3 style="text-align:left; color:#1E90FF;">
  5. Well Log Visualizations in Python
</h3>

Effective visualization is crucial in petrophysics. Matplotlib offers flexibility for custom log plots, while specialized libraries like mplstereonet enable advanced geological visualizations

<h3 style="text-align:left; color:#1E90FF;">
  6. Well Log Data Preprocessing
</h3>

Preprocessing is critical for machine learning applications. This includes handling missing data, removing noise, normalizing features, creating derived properties, and ensuring consistent sampling intervals.